inputs:
  platform:
    description: platform
    required: true
  version:
    description: version
    required: true
runs:
  using: composite
  steps:
    - name: install
      if: inputs.platform == 'windows.amd64'
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '[${{ inputs.version }},'
        msbuild-architecture: x64
    - name: check
      shell: bash
      run: |
        MSBuild -version
