name: download_certificate xx
description: _
inputs:
  source_file_pfx:
    required: true
  source_password_pfx:
    required: true
  source_file_jks:
    required: true
  source_password_jks:
    required: true
  destination:
    required: true
runs:
  using: composite
  steps:
    - name: download
      if: ${{ true }}
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Force -Path "${{ inputs.destination }}"
        Set-Content -AsByteStream -Path "${{ inputs.destination }}/file.pfx" -Value ([System.Convert]::FromBase64String("${{ inputs.source_file_pfx }}"))
        Set-Content -Encoding utf8 -NoNewline -Path "${{ inputs.destination }}/password.pfx.txt" -Value ("${{ inputs.source_password_pfx }}")
        Set-Content -AsByteStream -Path "${{ inputs.destination }}/file.jks" -Value ([System.Convert]::FromBase64String("${{ inputs.source_file_jks }}"))
        Set-Content -Encoding utf8 -NoNewline -Path "${{ inputs.destination }}/password.jks.txt" -Value ("${{ inputs.source_password_jks }}")
    - name: check
      if: ${{ true }}
      shell: pwsh
      run: |
        Get-ChildItem -Recurse -Path "${{ inputs.destination }}"
