inputs:
  destination:
    description: destination
    required: true
runs:
  using: composite
  steps:
    - name: download
      shell: pwsh
      run: |
        mkdir -p ${{ inputs.destination }}
        echo -n "MQ==" | base64 -d > ${{ inputs.destination }}/file.pfx
        echo -n "MQ==" | base64 -d > ${{ inputs.destination }}/password.pfx.txt
        echo -n "MQ==" | base64 -d > ${{ inputs.destination }}/file.jks
        echo -n "MQ==" | base64 -d > ${{ inputs.destination }}/password.jks.txt
        ls ${{ inputs.destination }}
