inputs:
  destination:
    description: destination
    required: true
runs:
  using: composite
  steps:
    - name: download
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Force -Path "${{ inputs.destination }}"
        Set-Content -AsByteStream -Path "${{ inputs.destination }}/file.pfx" -Value ([System.Convert]::FromBase64String("MQ=="))
        Set-Content -AsByteStream -Path "${{ inputs.destination }}/password.pfx.txt" -Value ([System.Convert]::FromBase64String("MQ=="))
        Set-Content -AsByteStream -Path "${{ inputs.destination }}/file.jks" -Value ([System.Convert]::FromBase64String("MQ=="))
        Set-Content -AsByteStream -Path "${{ inputs.destination }}/password.jks.txt" -Value ([System.Convert]::FromBase64String("MQ=="))
    - name: check
      shell: pwsh
      run: |
        Get-ChildItem -Recurse -Path "${{ inputs.destination }}"
