inputs:
  host:
    description: host
    required: true
  version:
    description: version
    required: true
runs:
  using: composite
  steps:
    - name: install
      if: inputs.host == 'windows' || inputs.host == 'linux' || inputs.host == 'macintosh'
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: ${{ inputs.version }}
    - name: install
      if: inputs.host == 'linux'
      shell: pwsh
      run: |
        sudo apt install libgtk-3-dev
    - name: check
      if: inputs.host == 'windows' || inputs.host == 'linux' || inputs.host == 'macintosh'
      shell: pwsh
      run: |
        flutter doctor -v
