inputs:
  platform:
    description: platform
    required: true
  version:
    description: version
    required: true
runs:
  using: composite
  steps:
    - name: install
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: ${{ inputs.version }}
    - name: install
      if: inputs.platform == 'linux.amd64'
      shell: pwsh
      run: |
        sudo apt install gtk+-3.0
    - name: check
      shell: pwsh
      run: |
        flutter doctor -v
