inputs:
  platform:
    description: platform
    required: true
  version:
    description: version
    required: true
runs:
  using: composite
  steps:
    - name: install
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: ${{ inputs.version }}.x
    - name: check
      shell: bash
      run: |
        flutter doctor -v
