inputs:
  platform:
    description: platform
    required: true
  version:
    description: version
    required: true
runs:
  using: composite
  steps:
    - name: install
      shell: pwsh
      run: |
        npm list -g
        npm install -g typescript@${{ inputs.version }}
    - name: check
      shell: pwsh
      run: |
        npm list -g
        tsc --version