inputs:
  host:
    description: host
    required: true
  version:
    description: version
    required: true
runs:
  using: composite
  steps:
    - name: install
      if: inputs.host == 'windows' || inputs.host == 'linux' || inputs.host == 'macintosh'
      shell: pwsh
      run: |
        npm install -g typescript@${{ inputs.version }}
    - name: check
      if: inputs.host == 'windows' || inputs.host == 'linux' || inputs.host == 'macintosh'
      shell: pwsh
      run: |
        tsc --version
