inputs:
  platform:
    description: platform
    required: true
  version:
    description: version
    required: true
runs:
  using: composite
  steps:
    - id: check
      shell: pwsh
      run: |
        echo $env:ANDROID_HOME
        Get-ChildItem -Path $env:ANDROID_HOME/cmdline-tools
        sdkmanager --version
        sdkmanager --install cmdline-tools;12.0
        sdkmanager --version
        sdkmanager --install platform-tools platforms;android-35 build-tools;35.0.0
        apksigner --version
