inputs:
  platform:
    description: platform
    required: true
  version:
    description: version
    required: true
runs:
  using: composite
  steps:
    - name: xx
      shell: pwsh
      run: |
        Add-Content -Encoding utf8 -Path $env:GITHUB_PATH -Value "$env:ANDROID_HOME/cmdline-tools/latest/bin"
        Add-Content -Encoding utf8 -Path $env:GITHUB_PATH -Value "$env:ANDROID_HOME/build-tools/35.0.0"
    - name: check
      shell: pwsh
      run: |
        echo $env:ANDROID_HOME
        Get-Content -Path $env:GITHUB_PATH
        sdkmanager --version
        sdkmanager --install "platform-tools" "platforms;android-35" "build-tools;35.0.0"
        apksigner --version
