inputs:
  enss:
    required: true
    type: boolean
  path:
    required: true
  target:
    required: true
  action_destination:
    required: false
  webdav_endpoint:
    required: false
  webdav_username:
    required: false
  webdav_password:
    required: false
  webdav_destination:
    required: false
runs:
  using: composite
  steps:
    - name: upload
      if: ${{ fromJSON(inputs.enss) }}
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.action_destination }}
        path: ${{ inputs.path }}
    - name: upload
      if: ${{ fromJSON(inputs.enss) }}
      uses: bxb100/action-upload@v0
      with:
        provider: webdav
        provider_options: |
          endpoint=${{ inputs.webdav_endpoint }}
          username=${{ inputs.webdav_username }}
          password=${{ inputs.webdav_password }}
          root=${{ inputs.webdav_destination }}
        include: ${{ inputs.path }}
