inputs:
  platform:
    description: platform
    required: true
  version:
    description: version
    required: true
runs:
  using: composite
  steps:
    - name: install
      shell: pwsh
      run: |
        brew install create-dmg
    - name: check
      shell: pwsh
      run: |
        create-dmg --version
