inputs:
  platform:
    description: platform
    required: true
  version:
    description: version
    required: true
  windows_version:
    description: windows version
    required: true
runs:
  using: composite
  steps:
    - name: install
      if: inputs.platform == 'windows.amd64'
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Force -Path "$env:GITHUB_WORKSPACE/.local/development"
        Invoke-WebRequest -Uri "https://github.com/mstorsjo/llvm-mingw/releases/download/${{ inputs.windows_version }}/llvm-mingw-${{ inputs.windows_version }}-ucrt-x86_64.zip" -OutFile "$env:GITHUB_WORKSPACE/.local/development/llvm-mingw.zip"
        Expand-Archive -Force -Path "$env:GITHUB_WORKSPACE/.local/development/llvm-mingw.zip" -DestinationPath "$env:GITHUB_WORKSPACE/.local/development/llvm-mingw"
        Remove-Item "$env:GITHUB_WORKSPACE/.local/development/llvm-mingw.zip"
        Add-Content -Encoding utf8 -Path $env:GITHUB_PATH -Value "$env:GITHUB_WORKSPACE/.local/development/llvm-mingw/bin"
    - name: install
      if: inputs.platform == 'linux.amd64'
      shell: pwsh
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 21
    - name: install
      if: inputs.platform == 'macintosh.arm64'
      shell: pwsh
      run: |
        brew update
        brew install llvm@21
    - name: install
      if: inputs.platform == 'android.amd64'
      shell: pwsh
      run: |
        echo "unneeded"
    - name: install
      if: inputs.platform == 'iphone.amd64'
      shell: pwsh
      run: |
        brew update
        brew install llvm@21
    - name: check
      shell: pwsh
      run: |
        echo $env:PATH
        clang --version
        clang-21 --version
        llvm-strip --version