inputs:
  host:
    description: host
    required: true
  version:
    description: version
    required: true
runs:
  using: composite
  steps:
    - name: install
      if: ${{ inputs.host == 'macintosh' }}
      shell: pwsh
      run: |
        brew install ldid
    - name: check
      if: ${{ inputs.host == 'macintosh' }}
      shell: pwsh
      run: |
        ldid
