inputs:
  host_platform:
    required: true
  version:
    required: true
runs:
  using: composite
  steps:
    - name: install
      if: ${{ inputs.host_platform == 'windows' || inputs.host_platform == 'linux' || inputs.host_platform == 'macintosh' }}
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: ${{ inputs.version }}
    - name: check
      if: ${{ inputs.host_platform == 'windows' || inputs.host_platform == 'linux' || inputs.host_platform == 'macintosh' }}
      shell: pwsh
      run: |
        xmake --version
