inputs:
  platform:
    description: platform
    required: true
  version:
    description: version
    required: true
runs:
  using: composite
  steps:
    - id: install
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r${{ inputs.version }}
        add-to-path: false
        link-to-sdk: false
    - id: check
      shell: pwsh
      run: |
        echo $env:ANDROID_NDK_HOME
        Get-Content -Path $env:GITHUB_ENV
        Add-Content -Encoding utf8 -Path $env:GITHUB_ENV -Value "ANDROID_NDK_HOME=${{ steps.install.outputs.ndk-path }}"
        echo $env:ANDROID_NDK_HOME
        Get-Content -Path $env:GITHUB_ENV
        Get-ChildItem -Path "${{ steps.install.outputs.ndk-path }}"
        echo $env:PATH
        apksigner --version
