inputs:
  platform:
    description: platform
    required: true
  version:
    description: version
    required: true
runs:
  using: composite
  steps:
    - name: install
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r${{ inputs.version }}
        add-to-path: false
    - name: check
      shell: pwsh
      run: |
        echo $env:ANDROID_NDK_HOME
        echo $env:GITHUB_ENV
        echo $env:PATH
        apksigner --version
