on:
  workflow_call:
    inputs:
      platform:
        description: platform
        required: true
        type: string
    secrets:
      certificate_file_pfx:
        description: certificate_file_pfx
        required: false
      certificate_password_pfx:
        description: certificate_password_pfx
        required: false
      certificate_file_jks:
        description: certificate_file_jks
        required: false
      certificate_password_jks:
        description: certificate_password_jks
        required: false
env:
  host: |-
    ${{ fromJSON('{
      "windows.amd64": "windows",
      "linux.amd64": "linux",
      "macintosh.arm64": "macintosh",
      "android.arm64": "windows",
      "iphone.arm64": "macintosh"
    }')[inputs.platform] }}
jobs:
  build:
    runs-on: |-
      ${{ fromJSON('{
        "windows.amd64": "windows-2025-vs2026",
        "linux.amd64": "ubuntu-24.04",
        "macintosh.arm64": "macos-26",
        "android.arm64": "windows-2025-vs2026",
        "iphone.arm64": "macos-26"
      }')[inputs.platform] }}
    env:
      repository_name: Twinning
      repository_path: ${{ github.workspace }}/Twinning
      repository_url: https://github.com/twinstar6980/Twinning
    steps:
      - name: check out
        uses: actions/checkout@v4
      - name: setup python
        if: ${{ inputs.platform == 'windows.amd64' || inputs.platform == 'linux.amd64' || inputs.platform == 'macintosh.arm64' || inputs.platform == 'android.arm64' || inputs.platform == 'iphone.arm64' }}
        uses: ./.github/actions/setup_python
        with:
          host: ${{ env.host }}
          version: '3.14.3'
      - name: setup windows-sdk
        if: ${{ inputs.platform == 'windows.amd64' }}
        uses: ./.github/actions/setup_windowssdk
        with:
          host: ${{ env.host }}
          version: '26100'
      - name: setup android-sdk
        if: ${{ inputs.platform == 'android.arm64' }}
        uses: ./.github/actions/setup_androidsdk
        with:
          host: ${{ env.host }}
          version: '36.1'
          build_version: '36.1.0'
          ndk_version: '29.0.14206865'
      - name: setup llvm
        if: ${{ inputs.platform == 'windows.amd64' || inputs.platform == 'linux.amd64' || inputs.platform == 'macintosh.arm64' || inputs.platform == 'iphone.arm64' }}
        uses: ./.github/actions/setup_llvm
        with:
          host: ${{ env.host }}
          version: '21'
          windows_version: '21.1.8-20251216'
      - name: setup xmake
        if: ${{ inputs.platform == 'windows.amd64' || inputs.platform == 'linux.amd64' || inputs.platform == 'macintosh.arm64' || inputs.platform == 'android.arm64' || inputs.platform == 'iphone.arm64' }}
        uses: ./.github/actions/setup_xmake
        with:
          host: ${{ env.host }}
          version: '3.0.7'
      - name: setup typescript
        if: ${{ inputs.platform == 'windows.amd64' || inputs.platform == 'linux.amd64' || inputs.platform == 'macintosh.arm64' || inputs.platform == 'android.arm64' || inputs.platform == 'iphone.arm64' }}
        uses: ./.github/actions/setup_typescript
        with:
          host: ${{ env.host }}
          version: '5.9.3'
      - name: setup flutter
        if: ${{ inputs.platform == 'windows.amd64' || inputs.platform == 'linux.amd64' || inputs.platform == 'macintosh.arm64' || inputs.platform == 'android.arm64' || inputs.platform == 'iphone.arm64' }}
        uses: ./.github/actions/setup_flutter
        with:
          host: ${{ env.host }}
          version: '3.41.4'
      - name: setup msbuild
        if: ${{ inputs.platform == 'windows.amd64' }}
        uses: ./.github/actions/setup_msbuild
        with:
          host: ${{ env.host }}
          version: '18.3.0'
      - name: setup xcode
        if: ${{ inputs.platform == 'macintosh.arm64' || inputs.platform == 'iphone.arm64' }}
        uses: ./.github/actions/setup_xcode
        with:
          host: ${{ env.host }}
          version: '26.3'
      - name: setup create-dmg
        if: ${{ inputs.platform == 'macintosh.arm64' }}
        uses: ./.github/actions/setup_createdmg
        with:
          host: ${{ env.host }}
          version: 'latest'
      - name: setup ldid
        if: ${{ inputs.platform == 'iphone.arm64' }}
        uses: ./.github/actions/setup_ldid
        with:
          host: ${{ env.host }}
          version: 'latest'
      - name: clone
        shell: pwsh
        run: |
          git clone "${{ env.repository_url }}"
      - name: download certificate
        # if: ${{ ${{ secrets.certificate_file_pfx != '' && secrets.certificate_password_pfx != '' && secrets.certificate_file_jks != '' && secrets.certificate_password_jks != '' }} }}
        uses: ./.github/actions/download_certificate
        with:
          source_file_pfx: ${{ secrets.certificate_file_pfx }}
          source_password_pfx: ${{ secrets.certificate_password_pfx }}
          source_file_jks: ${{ secrets.certificate_file_jks }}
          source_password_jks: ${{ secrets.certificate_password_jks }}
          destination: ${{ env.repository_path }}/.local/certificate
      - name: build
        shell: pwsh
        run: |
          python3 "${{ env.repository_path }}/BUILD.py" "${{ inputs.platform }}"
      - name: upload
        uses: actions/upload-artifact@v6
        with:
          name: ${{ inputs.platform }}.zip
          path: |
            ${{ env.repository_path }}/.local/distribution/${{ inputs.platform }}.bundle.zip
