name: distribute
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        include:
          - target_platform: windows.amd64
            github_os: windows-2025-vs2026
    runs-on: ${{matrix.github_os}}
    env:
      repository_name: KairosoftGameManager
      repository_path: ${{env:repository_path}}
      repository_url: https://github.com/twinstar6980/KairosoftGameManager
    steps:
      - name: chech out
        uses: actions/checkout@v4
      - name: prepare MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '[18.0,'
          msbuild-architecture: x64
      - name: clone
        shell: bash
        run: |
          git clone ${{env:repository_url}}
      # - name: restore certificate
      #   shell: bash
      #   run: |
      #     mkdir ${{env:repository_path}}/.local
      #     mkdir ${{env:repository_path}}/.local/certificate
      #     echo -n "${{ secrets.CERTIFICATE_FILE_PFX     }}" | base64 -d > ${{env:repository_path}}/.local/certificate/file.pfx
      #     echo -n "${{ secrets.CERTIFICATE_PASSWORD_PFX }}" | base64 -d > ${{env:repository_path}}/.local/certificate/password.pfx.txt
      #     echo -n "${{ secrets.CERTIFICATE_FILE_JKS     }}" | base64 -d > ${{env:repository_path}}/.local/certificate/file.jks
      #     echo -n "${{ secrets.CERTIFICATE_PASSWORD_JKS }}" | base64 -d > ${{env:repository_path}}/.local/certificate/password.jks.txt
      - name: distribute
        run: |
          cd ${{env:repository_path}}
          python3 ./DISTRIBUTE.py ${{matrix.target_platform}}
      - name: upload
        uses: actions/upload-artifact@v6
        with:
          name: ${{matrix.target_platform}}.zip
          path: |
            ${{env:repository_path}}/.local/distribution
