name: distribute
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        include:
          - target_platform: windows.amd64
            github_os: windows-latest
          - target_platform: linux.amd64
            github_os: ubuntu-latest
          - target_platform: macintosh.arm64
            github_os: macos-latest
          - target_platform: android.arm64
            github_os: ubuntu-latest
          - target_platform: iphone.arm64
            github_os: macos-latest
    runs-on: ${{ matrix.github_os }}
    steps:
