name: distribute
on:
  workflow_dispatch:
    inputs:
      platform:
        description: platform
        required: true
        type: choice
        options:
          - windows.amd64
          - linux.amd64
          - macintosh.arm64
          - android.arm64
          - iphone.arm64
defaults:
  run:
    shell: pwsh
jobs:
  test1:
    runs-on: windows-2025-vs2026
    steps:
      - name: check out
        uses: actions/checkout@v4
      - name: setup windows-sdk
        if: inputs.platform == 'windows.amd64'
        uses: ./.github/actions/setup_androidsdk
        with:
          platform: ${{ inputs.platform }}
          version: '14742923'
      - name: setup android-ndk
        if: inputs.platform == 'windows.amd64'
        uses: ./.github/actions/setup_androidndk
        with:
          platform: ${{ inputs.platform }}
          version: '29'
      - name: setup llvm
        if: inputs.platform == 'windows.amd64'
        uses: ./.github/actions/setup_llvm
        with:
          platform: ${{ inputs.platform }}
          version: '21'
      # - name: setup windows-sdk
      #   if: inputs.platform == 'windows.amd64'
      #   uses: ./.github/actions/setup_windowssdk
      #   with:
      #     platform: ${{ inputs.platform }}
      #     version: '26100'
      # - name: download certificate
      #   uses: ./.github/actions/download_certificate
      #   with:
      #     destination: ${{ matrix.repository_path }}/.local/distribution
      # - name: setup msbuild
      #   if: inputs.platform == 'windows.amd64'
      #   uses: ./.github/actions/setup_msbuild
      #   with:
      #     platform: ${{ inputs.platform }}
      #     version: '18.3.0'
      # - name: setup xmake
      #   uses: ./.github/actions/setup_xmake
      #   with:
      #     platform: ${{ inputs.platform }}
      #     version: '3.0.7'
      # - name: setup flutter
      #   uses: ./.github/actions/setup_flutter
      #   with:
      #     platform: ${{ inputs.platform }}
      #     version: '3.41.4'
      # - name: setup python
      #   uses: ./.github/actions/setup_python
      #   with:
      #     platform: ${{ inputs.platform }}
      #     version: '3.14.3'
  # build:
  #   strategy:
  #     matrix:
  #       include:
  #         - platform: windows.amd64
  #           github_os: windows-2025-vs2026
  #           repository_name: KairosoftGameManager
  #           repository_path: ./KairosoftGameManager
  #           repository_url: https://github.com/twinstar6980/KairosoftGameManager
  #   runs-on: ${{matrix.github_os}}
  #   steps:
  #     - name: chech out
  #       uses: actions/checkout@v4
  #     - name: clone
  #       shell: pwsh
  #       run: |
  #         git clone ${{matrix.repository_url}}
  #     # - name: distribute
  #     #   shell: pwsh
  #     #   run: |
  #     #     cd ${{matrix.repository_path}}
  #     #     python3 ./DISTRIBUTE.py ${{matrix.platform}}
  #     - name: upload
  #       uses: actions/upload-artifact@v6
  #       with:
  #         name: ${{matrix.platform}}.zip
  #         path: |
  #           ${{matrix.repository_path}}/.local/distribution
