name: KairosoftGameManager - distribute
on:
  workflow_call:
    inputs:
      repository_url:
        required: true
        type: string
      target_platform:
        required: true
        type: string
      enable_certificate:
        required: true
        type: boolean
      enable_webdav:
        required: true
        type: boolean
    secrets:
      certificate_file_pfx:
        required: false
      certificate_password_pfx:
        required: false
      certificate_file_jks:
        required: false
      certificate_password_jks:
        required: false
      webdav_endpoint:
        required: false
      webdav_username:
        required: false
      webdav_password:
        required: false
env:
  host_platform: |-
    ${{ fromJSON('{
      "windows.amd64": "windows",
    }')[inputs.target_platform] }}
jobs:
  main:
    runs-on: |-
      ${{ fromJSON('{
        "windows.amd64": "windows-2025-vs2026",
      }')[inputs.target_platform] }}
    steps:
      - name: check out
        if: ${{ true }}
        uses: actions/checkout@v4
      - name: setup python
        if: ${{ inputs.target_platform == 'windows.amd64' }}
        uses: ./.github/actions/setup_python
        with:
          host_platform: ${{ env.host_platform }}
          version: '3.14.3'
      - name: setup windows-sdk
        if: ${{ inputs.target_platform == 'windows.amd64' }}
        uses: ./.github/actions/setup_windowssdk
        with:
          host_platform: ${{ env.host_platform }}
          version: '26100'
      - name: setup msbuild
        if: ${{ inputs.target_platform == 'windows.amd64' }}
        uses: ./.github/actions/setup_msbuild
        with:
          host_platform: ${{ env.host_platform }}
          version: '18.3.0'
      - name: clone repository
        if: ${{ true }}
        shell: pwsh
        run: |
          git clone "${{ inputs.repository_url }}" "${{ github.workspace }}/repository"
      - name: download certificate
        if: ${{ inputs.enable_certificate }}
        uses: ./.github/actions/download_certificate
        with:
          source_file_pfx: ${{ secrets.certificate_file_pfx }}
          source_password_pfx: ${{ secrets.certificate_password_pfx }}
          source_file_jks: ${{ secrets.certificate_file_jks }}
          source_password_jks: ${{ secrets.certificate_password_jks }}
          destination: ${{ github.workspace }}/repository/.local/certificate
      - name: build repository
        if: ${{ true }}
        shell: pwsh
        run: |
          python3 "${{ github.workspace }}/repository/BUILD.py" "${{ inputs.target_platform }}"
      - name: upload to webdav
        if: ${{ inputs.enable_webdav }}
        uses: ./.github/actions/upload_file
        with:
          path: ${{ github.workspace }}/repository/.local/distribution/*
          target: webdav
          webdav_endpoint: ${{ secrets.webdav_endpoint }}
          webdav_username: ${{ secrets.webdav_username }}
          webdav_password: ${{ secrets.webdav_password }}
          webdav_destination: '/ghatest'
      - name: upload to action
        if: ${{ true }}
        uses: ./.github/actions/upload_file
        with:
          path: ${{ github.workspace }}/repository/.local/distribution/*
          target: action
          action_destination: ${{ inputs.target_platform }}.distribution
