on:
  workflow_dispatch:
    inputs:
      build_windows_amd64:
        description: build_windows_amd64
        required: true
        type: boolean
        default: false
      build_linux_amd64:
        description: build_linux_amd64
        required: true
        type: boolean
        default: false
      build_macintosh_arm64:
        description: build_macintosh_arm64
        required: true
        type: boolean
        default: false
      build_android_arm64:
        description: build_android_arm64
        required: true
        type: boolean
        default: false
      build_iphone_arm64:
        description: build_iphone_arm64
        required: true
        type: boolean
        default: false
jobs:
  build:
    strategy:
      matrix:
        include:
          - enabled: ${{ inputs.build_windows_amd64 }}
            platform: windows.amd64
          - enabled: ${{ inputs.build_linux_amd64 }}
            platform: linux.amd64
          - enabled: ${{ inputs.build_macintosh_arm64 }}
            platform: macintosh.arm64
          - enabled: ${{ inputs.build_android_arm64 }}
            platform: android.arm64
          - enabled: ${{ inputs.build_iphone_arm64 }}
            platform: iphone.arm64
    if: ${{ matrix.enabled }}
    uses: ./.github/workflows/build.yml
    with:
      platform: ${{ matrix.platform }}
    secrets: inherit
