on:
  workflow_dispatch:
    inputs:
      build_windows_amd64:
        required: true
        type: boolean
        default: false
jobs:
  build_windows_amd64:
    if: ${{ inputs.build_windows_amd64 }}
    uses: ./.github/workflows/build.yml
    with:
      platform: windows.amd64
    secrets: inherit
